services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  nestjs-app:
    build: .
    container_name: nestjs_app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '5000:5000'
    command: npm run migrate:latest && npm run start:prod

volumes:
  pgdata:
